---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: jellyfin
      version: 23.7.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Berlin
    global:
      stopAll: false
    persistence:
      media:
        enabled: true
        existingClaim: media-nfs-pvc
        mountPath: /mnt/media
      data:
        volsync:
          - name: backup
            type: restic
            credentials: garage
            dest:
              enabled: true
            src:
              enabled: false
              trigger:
                schedule: 6 0 * * *
      config:
        volsync:
          - name: backup
            type: restic
            credentials: garage
            dest:
              enabled: true
            src:
              enabled: false
              trigger:
                schedule: 5 0 * * *
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${JELLYFIN_IP}
        integrations:
          metallb:
            enabled: true
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: jellyfin.${DOMAIN_0}
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
    credentials:
      garage:
        type: s3
        url: ${GARAGE_S3_URL}
        bucket: ${GARAGE_S3_BUCKET}
        accessKey: ${GARAGE_S3_ACCESSKEY}
        secretKey: ${GARAGE_S3_SECRETKEY}
        encrKey: ${GARAGE_S3_ENCRYPTIONKEY}
