apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:bcm+jO+bvGI8GtzwaIBvwJE8TG4LH8h1V5yPXnvX9B/4WqLg3j90VZu+ffzLOZ8V0EyB6aFX3c3BdXSXDuubZa6HWTHAoU3QIicxASvJO3bfjTxoytQUaEBxRSrjyzBWaE7GSoGAsOKasUmuAGKze2kPInm0LwhAu1J5mUMgCFV2cPycB97+eG4KzniIzdTjJfZIpGRGHuhuJxwbMZiovs9jUYrgW1T76DkHZpHttW2mEYJtJT3/YlXtI7YLSUHySNqQgY3bO4r3NgdDsFcSajE2bMuP9XrW68Kc6tQKqXDWC7KvU3IBfBAe8eyv8VD2kGbQ5ncHOee2nhWnrU9Rd6mlhXKGKyp71IDydJz06W/n878vW5tAvBi6QZHohBLX,iv:Jzfn0CFWHxMN3DQ0/kDzf7mc9cFhsU85+LLNo9O+X9g=,tag:JIa4JOcJIkgpv3l2LwOQeQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:zrvVj9QKXW+UvNgycr8MiaNfkgmIEYe963AJXXalkwB/xSG4euKYdEaWeiAeLSDcUTESlZY23O+mLCeS0zH++yWv+YBFOb7g0epWafCTHgJQphi00u09khxrbNf2qo7lYheL5/3tp9BuEIBWGUoRe9BcgPUEn2kyWRaJe93KuRWjGn2sEYPqf3pnYIFGb1rQMP4QA/JNBu3qLIWGpaYgXt7+ehdztSWvxMqV1KvUKPu9YtUKw4caVO2myBq2sIwtTu1J1AHN9//3rafITQ==,iv:cLZbT3TmG3OKqJtwNapjAuqDzdh2tpBN9ULEcqXM+Kk=,tag:O3GaE/GphCBQqVmJaFn37Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:36jlfIyE7CWD0at1rWTG4gfCCA0AJYgxUqwYWONS4gvKuZ4nxdSv6i46W80fvez93JiUh1F5HYTeQgbIbnlcwaj9s44Ihmag/GEJHYbFbAyokG0O8pf4Zg9Lk7gpfqBC7OmikloevNmaSFhbUgZjiUEsR3aTO0kQXOZQki689z7/xME4gR3HmKCtIxjSvpwym8BFKEXsumSyDHqQtbyQonslw1rudGu4CDSo,iv:21Qoudk12xMnLRxOuh9zkbXDOFTmS52laI0qMMf+T4g=,tag:dg8uB4f2RDZPFXiCi5Fgaw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZXdtWVgwaDdLbW4vWnlX
            V3NoTHV4eCtBYVlIV21VRmpZMGhrRlRtU3lzCjdaRVg1SWEzSndIQmtiSzlxblln
            NzdmYlN6RXFidm9vazZDc3JGaVN1TWMKLS0tIEpUQzlTRDZmek13YUluS3pPS2Fm
            SEpXcXJOUGJoMG9DRVBkdnJjeTUvclEKKIUPNZ+o+Mbt5qsZIqBUh0oe2Y9rjk8v
            /hziAxbotNhcFD0TU6wFZv15BODRtMv+L0U6yU2vUwkYQ8Q8iDzMsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10em0ywlceeyjt6v07ef46nnyvwpfr2d9f6v53vayafpcqpcpkvsq55tuma
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-07T06:44:40Z"
    mac: ENC[AES256_GCM,data:78mG0Yzg/gX7HyB85PgHI8t6K7PkcB13NZilUPSma9X4mAKaRunfylsKyBGrlAfPHDzOWdaWaZEvvVjo5DdkUjYmWugL29rLlRAx6OayM9rtWmvn3CshTDlop+UzjNUUIYLi2CAz3GkpyMU9yuyQYdoixgZB/2NecfhzLu1WpWU=,iv:0+vHslfI6Pc2G70vhsPtbNjs/Itzhmjo4JvvrkPJ0lo=,tag:8ooRbgz5NI7ds2MRA1sDXQ==,type:str]
    shamir_threshold: 3
    version: 3.13.1
