apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:H7+V3epyo5FXJ/RvmXAVcWA5886Jgv6aJmVcHeMlKjGVlEnBa5vw0J5NTnxW4v435MDYa876L8scNjya+DakXU/8KWV/Pl8dPU5qDAFasCV1/iKOhFDY+uHMRfzHF9G3/mGFj23StvH1Ie2QF7JEsMPYZAwLYp9KjLrk0Yib3THzTGG7kbtugkEkA86NyfhfoXGZP9TP3amgnY/7e3/iUqeFIhGMndSqxdr0HX9SM2BAo3wXNQfz0qZCxuCQ1VTB8rViNU73k+JCxEwV0J91YGVx4YkGrnrO4W73P1i6mGr/Hbw8AL0rsNIvJ2PGA9vRVQzzfj5OpOEeaduKpYJfmaeoNj5OJ2064rOqOhOYxKiuedsnoqZbLiZwFrCHR3aj,iv:FoHgWied78kMYJwX/meOysehUEmwCS/0Egz0Z3c4008=,tag:Nr4SV8GO+hUPjejKJTWFLw==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZRieXJd8pgAhabpBcBFK/zMEHHg5/Zi1T4TelnqN8Idzm7+XNaPpE0wUCT/EQnPvNxpCHwV1w14QfCRMGFABtll6eSE1eNfQ2WOCcXsG7JDcm8sBwl08zXzX5/U4JSmjrcIMj9C8smrCstbOD+eCnXBLBoZU1ztdWEEpTwUYQJfwC4tAyr037miAezqZQ+wq52TuWLO2nmz+AEsItliGhPnz3/pPTiSXATRyGoipn9ipR/dTUZfZrTcMOr5oYbHUdVXCTgfDORj5zjLd/g==,iv:Bp8OYGUvoH9R/2w7YgE8+lSCAZQskoXuyoEdAnElpxA=,tag:rTZhqnbCqtLfvoR5GQh8Kw==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZUX07TK4KJ+l3mBEojVs7c7IQMC7ZIu2PCc2BvN75cK4+h2Hxyj9AiuxIBQKDX0WetLVLFiIK4dYLs5612akH6Sl+w3RpsIT//5NdXbpltgjpUhZAu/EWHc5Vi7geDo3J8BtKU+95OC6ob+VTw0j5rFzLPnAUxMTAK187fiwKOuw+dN9Ss0xz9VZmCZyw52+V+AenlCKRvhW3naljdUhbsXZK36jkDGEpXjq,iv:TdG0OwcmQS7R/XAOSUoxyrH2b2S28LF9s7IKm4gVpVQ=,tag:uWNliepVf5rqahVH4mf4Eg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTzlxSXFVdUl6ZlF5ZW9W
            RFJqSVJaYnNpZTg3Nm9BLy9vT1pIUlRndTB3CmRtSlp3Y1JIazJHK05LRGZKOFph
            RlpXbTJtZ2craUZzeUZhc2xMWUMzRWMKLS0tIHA1VXU0ODRVbjRVWnJVcTBNS3d2
            TWw1N0pwWDZPWGZHek1iZDUrMy91WmsK9ncp4to+gHHv+/KYw45iwCZkLs1vlzuS
            N62ZY84PVktYwHHNXu+M2T7V1ouARkEfz4e5in/aaZztkBO/QdGHkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10em0ywlceeyjt6v07ef46nnyvwpfr2d9f6v53vayafpcqpcpkvsq55tuma
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-02T20:02:38Z"
    mac: ENC[AES256_GCM,data:EEAS3IhkoeKJjLi/HEBCIkjG1tXU84Vgx4rNROngsmDCgJpGuEnyvSMl+78TweehK5KGvD2Gfqlf4u7Ag+o0oNsdsrpFVNrQ7rYYtwQccaDq+B04+U/ppZSl94D4CsOxbLrjUb5E392pjDbGI+cS+8qcuRrf7bYsjX3ty3kO544=,iv:UqZmVHEjg93BwXK9N/lMGEL9PA51iy4VNUHMhkukGRg=,tag:t4cqcEyqPeNgf0gT5YUPmg==,type:str]
    shamir_threshold: 3
    version: 3.13.1
