apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/VPmmzvabldGsiEgjapNPp7YVoWbxmv4dUSveIH6ydaepEN8xS36CNPb2Jnc9tFl43FKHeZ5MIFN7oyBkwPqzRl21BINSZHoLTWOiM6XWdFYkbH4wbAl8WF94ZBjaUnpg0LLeaiKBesDEtbJHF2P4hiQdONmNMg4rOpxsaf2VkK0uTIeihGyMy/OzKjLqom5z9VsIM3gaX0bt/aioHzVV6AJU2DyOms2+iv/gK9qkNlh9j59qkaTYRl4M/pS7tqtfmpF4FqjqsE/meC6WTll/25+Qnr+7vXdJHq9T6aMqD8Nt1tgWR9u9gFrazRZo5EYrxR/I5Z23wgI07CznD4za1oALGM8HmXqDGmlg3IwTzzwizFr/MvDaST7TxS/QXfH,iv:9JBBK5Z0Kw1iafOnMmk2EpBzBtVJRDCOTRbw1l1rY9E=,tag:hPrrv5VWHbb6/Hy7orzzIA==,type:str]
    identity.pub: ENC[AES256_GCM,data:AgOWksyHLGmCnTnzHjoVr0PNJwxGnVpNQErIkBUBwjteCApP1b201pPSxooMFM7U7dio4orrP4dUO6fl08btTLFpN8DrN5BMBn2LwoebOZQBeK+c91ldQGF0TYara9ymQCvPkS+N6+lp/d3NtJG/Ay1cgpjf5z0GMJLgOcLosh1mCslnDVqo/86vQeGfBL2xroqAaLopdMyY15vmeBF8rFJaP4RBjlzprWGg3VQlLWYn5UeCAcl+hMX4P14H5MxOSV5cG0+7dATLJpxJew==,iv:j5oBBBEZMwbYjA9a317ucEoZmZkO9QUdMw3r0W6uQSw=,tag:NRs/gMkIi3DGZT9V6Q5o5Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:kPPBQmI4cZ1ks7L7GbrgNtv/Axp0CpaIecdTDZyDU6AWX+lxQb/snhj500PvbwRjgqnATapLJH5buIzDiDQsYposiInxtV8UhEOpZ8v8u5Qn8j2E/dJzse/yDqRRARMGEy6sg1ydSPVyBz9LHmZ85FTzjUWpExKylR7PnyBcNnuXeJL2H3RUV5thvVPwtNbxxBgLUbkuhs0MP2P6gj/lhDhEB8tuy0lMSG0Z,iv:z8cb5vfgWwtUfdh19V9aqxOFxAqs7/7m+B4XlzI5Ubk=,tag:AKpPJoIs5BQeQadEtpyMIg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArY1BlSjF4empNUzZJMWVO
            blR3SHRFRDRJcC9HWEM0bGp2cXRCV2oxUjNBCnhQeDV2eFVXVHplb2tYN3V4Lytu
            QjJMcFlBUVJJMERwcWQ4dGhuRVFlYlkKLS0tIHFnNlRxaXhEVldvVTdna01ab0VC
            T0NBRHh4OWNteFFLeThtZVZMMHNuZVEKbxwtXklzGMER7zMSI/ZTB86//zw74UxA
            GRjzAS5GAYOG48OO/SUK7gJc/M1gkr4sAwdPcPxAUZzMVSynPooS5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10em0ywlceeyjt6v07ef46nnyvwpfr2d9f6v53vayafpcqpcpkvsq55tuma
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-06T13:35:08Z"
    mac: ENC[AES256_GCM,data:E0UfI2PvtwiAA6D2Z3idYFd9wzv2li412MAWV0gdNUAykSE0nR4eLzA5j+HKLT19rvEu0gjiDpg6bctNPcTIdJPxN4xi87jk50Gn8uY0G4GPP01o7ovmFDkNCf4MPzTBSeMOHzh8k6qMU9WG1uKRhT5P0kzMRnPAsDoc0ydFyAc=,iv:dCdV565BSj68MC/cE2q7eLwmk4DiQ4NDj2vntUyRB64=,tag:aaLUvRfnRjCaqwXQvE6QrA==,type:str]
    shamir_threshold: 3
    version: 3.13.1
