---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi
  namespace: unifi
spec:
  interval: 15m
  chart:
    spec:
      chart: unifi
      version: 26.14.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Berlin
    global:
      stopAll: false
    persistence:
      data:
        volsync:
          - name: backup
            type: restic
            credentials: garage
            dest:
              enabled: true
            src:
              enabled: false
              trigger:
                schedule: 32 0 * * *
        targetSelector:
          main:
            main:
              mountPath: /usr/lib/unifi/olddata
    service:
      comm:
        type: LoadBalancer
        loadBalancerIP: ${UNIFI_IP}
        integrations:
          metallb:
            enabled: true
      stun:
        type: LoadBalancer
        loadBalancerIP: ${UNIFI_IP}
        integrations:
          metallb:
            enabled: true
      speedtest:
        type: LoadBalancer
        loadBalancerIP: ${UNIFI_IP}
        integrations:
          metallb:
            enabled: true
      guestportal:
        type: LoadBalancer
        loadBalancerIP: ${UNIFI_IP}
        integrations:
          metallb:
            enabled: true
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
          - host: unifi.${DOMAIN_0}
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
    credentials:
      garage:
        type: s3
        url: ${GARAGE_S3_URL}
        bucket: ${GARAGE_S3_BUCKET}
        accessKey: ${GARAGE_S3_ACCESSKEY}
        secretKey: ${GARAGE_S3_SECRETKEY}
        encrKey: ${GARAGE_S3_ENCRYPTIONKEY}
